-- MySQL Script generated by MySQL Workbench
-- So 22 Mär 2015 20:59:00 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Author` (
  `idAuthor` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idAuthor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tweet` (
  `idTweet` INT NOT NULL,
  `message` VARCHAR(45) NULL,
  `numberOfRetweets` INT NULL,
  `temeStamp` VARCHAR(45) NULL,
  `Author_idAuthor` INT NOT NULL,
  PRIMARY KEY (`idTweet`, `Author_idAuthor`),
  INDEX `fk_Tweet_Author_idx` (`Author_idAuthor` ASC),
  CONSTRAINT `fk_Tweet_Author`
    FOREIGN KEY (`Author_idAuthor`)
    REFERENCES `mydb`.`Author` (`idAuthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hashtag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hashtag` (
  `idHashtag` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`idHashtag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tweet_has_Hashtag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tweet_has_Hashtag` (
  `Tweet_idTweet` INT NOT NULL,
  `Hashtag_idHashtag` INT NOT NULL,
  PRIMARY KEY (`Tweet_idTweet`, `Hashtag_idHashtag`),
  INDEX `fk_Tweet_has_Hashtag_Hashtag1_idx` (`Hashtag_idHashtag` ASC),
  INDEX `fk_Tweet_has_Hashtag_Tweet1_idx` (`Tweet_idTweet` ASC),
  CONSTRAINT `fk_Tweet_has_Hashtag_Tweet1`
    FOREIGN KEY (`Tweet_idTweet`)
    REFERENCES `mydb`.`Tweet` (`idTweet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tweet_has_Hashtag_Hashtag1`
    FOREIGN KEY (`Hashtag_idHashtag`)
    REFERENCES `mydb`.`Hashtag` (`idHashtag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trending`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trending` (
  `idTrending` INT NOT NULL,
  `timeStamp` VARCHAR(45) NULL,
  `Hashtag_idHashtag1` INT NOT NULL,
  `Hashtag_idHashtag2` INT NOT NULL,
  PRIMARY KEY (`idTrending`, `Hashtag_idHashtag1`, `Hashtag_idHashtag2`),
  INDEX `fk_Trending_Hashtag1_idx` (`Hashtag_idHashtag1` ASC),
  INDEX `fk_Trending_Hashtag2_idx` (`Hashtag_idHashtag2` ASC),
  CONSTRAINT `fk_Trending_Hashtag1`
    FOREIGN KEY (`Hashtag_idHashtag1`)
    REFERENCES `mydb`.`Hashtag` (`idHashtag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trending_Hashtag2`
    FOREIGN KEY (`Hashtag_idHashtag2`)
    REFERENCES `mydb`.`Hashtag` (`idHashtag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
